import React, { useState, ChangeEvent } from "react";

import styles from "./Login.module.css";
import { Link, useNavigate } from "react-router-dom";
import { emailRegex, passwordRegex } from "../../Utils/RegEx";
import toast from "react-hot-toast";
import axios from "axios";
import {
  FacebookLoginButton,
  GoogleLoginButton,
} from "react-social-login-buttons";

import { LoginSocialFacebook } from "reactjs-social-login";

import { useGoogleLogin } from "@react-oauth/google";
import Loader from "../Loader/Loader";

const Login = () => {
  //---------------------------
  const navigate = useNavigate(); // to navigate user to specific link
  //---------------------------
  const [userDetails, setuserDetails] = useState({
    email: "",
    password: "",
  });

  const [isLoading, setisLoading] = useState(false);
  const [show, setshow] = useState(false);

  function handleInputChange(event: ChangeEvent<HTMLInputElement>): void {
    const { name, value } = event.target;
    setuserDetails((prev) => ({ ...prev, [name]: value }));
    console.log(userDetails);
  }

  const handleLogin = async () => {
    if (!emailRegex.test(userDetails.email)) {
      toast.error("Please enter a valid email address");
      return;
    }
    if (!passwordRegex.test(userDetails.password)) {
      toast.error(
        "Password must be at least 8 characters and must include at lease one speacial character and one number"
      );
      return;
    }
    try {
      setisLoading(true);
      const response = await axios.post(
        `${import.meta.env.VITE_BASE_URL}/user/login`,
        userDetails
      );
      console.log(response);
      // lấy dữ liệu từ json - message từ server
      toast.success(response.data.message);

      // local storage - save token
      localStorage.setItem("token", response.data.token);
      navigate("/home");
      setisLoading(false);
    } catch (error: any) {
      toast.error(error.response.data.message);
      console.log(error);
      setisLoading(false);
    }
    // toast.success("FORM SUBMITED");
    // console.log(emailRegex.test(userDetails.email));
    // console.log(passwordRegex.test(userDetails.password), userDetails.password);
  };

  const handleContinueWithGoogle = useGoogleLogin({
    onSuccess: async (response: any) => {
      console.log(response);

      const res = await axios.get(
        "https://www.googleapis.com/oauth2/v3/userinfo",
        { headers: { Authorization: `Bearer ${response.access_token}` } }
      );

      console.log(res.data);

      // Create new User
      const newUser = {
        username: res.data.name,
        email: res.data.email,
        autoGenerated: true,
      };
      console.log(newUser);

      // call APT to backend
      try {
        const response = await axios.post(
          `${import.meta.env.VITE_BASE_URL}/user/login`,
          newUser
        );
        console.log(response);
        // lấy dữ liệu từ json - message từ server
        toast.success(response.data.message);

        // local storage - save token
        localStorage.setItem("token", response.data.token);
        navigate("/home");
        setisLoading(false);
      } catch (error: any) {
        toast.error(error.response.data.message);
        console.log(error);
        setisLoading(false);
      }
    },
    onError: (error: any) => {
      console.log(error);
    },
  });

  const handleContinueWithFacebook = async (res) => {
    const newUser = {
      username: res.data.name,
      email: res.data.email,
      autoGenerated: true,
    };

    console.log(newUser);

    try {
      const response = await axios.post(
        `${import.meta.env.VITE_BASE_URL}/user/login`,
        newUser
      );
      console.log(response);

      toast.success(response.data.message);

      localStorage.setItem("token", response.data.token);
      navigate("/home");
      setisLoading(false);
    } catch (error: any) {
      toast.error(error.response.data.message);
      console.log(error);
      setisLoading(false);
    }
  };

  //-----------------------------------------
  return (
    // full page
    <div className={styles.container}>
      {/* container - Form */}
      <div className={styles.formContainer}>
        <h2>Login ...</h2>

        <div className={styles.social}>
          <div>
            <LoginSocialFacebook
              appId={import.meta.env.VITE_FACEBOOK_CLIENT_ID}
              onResolve={(res) => {
                setisLoading(true);
                handleContinueWithFacebook(res);
              }}
              onReject={(err) => {
                console.log(err);
              }}
            >
              <FacebookLoginButton>Continue with Facebook</FacebookLoginButton>
            </LoginSocialFacebook>
          </div>
          <div
            onClick={() => {
              setisLoading(true);
              handleContinueWithGoogle();
            }}
          >
            <GoogleLoginButton>Continue with Google</GoogleLoginButton>
          </div>
        </div>
        {/* control input */}
        <div className={styles.inputContainer}>
          <input
            value={userDetails.email}
            placeholder="Enter your email ..."
            type="email"
            name="email"
            onChange={handleInputChange}
          />
          <div className={styles.passwordContainer}>
            <input
              value={userDetails.password}
              placeholder="Enter your password ..."
              type={show ? "text" : "password"}
              name="password"
              onChange={handleInputChange}
            />
            <button
              onClick={() => {
                setshow(!show);
              }}
            >
              {show ? "HIDE" : "SHOW"}
            </button>
          </div>
          <button disabled={isLoading} onClick={handleLogin}>
            {isLoading ? <Loader /> : "LOGIN"}
          </button>
        </div>
        <div className={styles.footer}>
          <Link to="/signup">Don't have an account ? Signup</Link>
          <Link to="/forget-password">Forgot password</Link>
        </div>
      </div>
    </div>
  );
};

export default Login;
